// Copyright (c) 2026 Loopdive GmbH. Licensed under Apache-2.0 WITH LLVM-exception.

export {
  IR_STRING_CONCAT_FN,
  IR_STRING_CONCAT_MANY_PREFIX,
  irStringConcatManySymbol,
  IR_STRING_CONCAT_OWNED_FN,
  IR_STRING_REPEAT_FN,
  IR_STRING_REPEAT_COUNTED_NATIVE_FN,
  IR_COUNTED_STRING_REPEAT_I32_MAX,
  IR_COUNTED_STRING_REPEAT_NATIVE_MAX_RESULT_CODE_UNITS,
  irCountedStringRepeatFitsNativeKernel,
  IR_STRING_EQUALS_FN,
  IR_STRING_CHAR_AT_FN,
  IR_STRING_CHAR_CODE_AT_FN,
  IR_STRING_ITERATOR_CHAR_AT_FN,
  IR_STRING_LITERAL_MATERIALIZE_FN,
  IR_NUMBER_TO_STRING_FN,
  IR_NUMBER_TO_FIXED_FN,
  parseIrStringConcatManyArity,
  IR_STRING_RUNTIME,
  toIntegerOrInfinity,
  utf16CharCodeAt,
  utf16CharAt,
  repeatString,
} from "./core/string-runtime.js";
export type {
  IrStringRuntimeIntrinsic,
  IrStringEncoding,
  IrStringConcatMode,
  IrStringRuntimeOperand,
  IrStringRuntimeResult,
  IrStringIndexContract,
  IrStringRuntimeSpec,
  IrStringRepeatCountContract,
} from "./core/string-runtime.js";
